Initializer breaks application
Running the test application with this file in place generates an
error:

    undefined method `output_buffer=' for #<Thing::Cell:0xb5a2e184>

To fix the application, either comment-out the "include" statement
from the file, or delete the file. And then re-start Rails!